spring:
  application:
    name: service-feign
  mvc:
    view:
      prefix:  /WEB-INF/jsp/ 
      suffix: .jsp
    hello :  Hello Angel From application  
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}     
server:
  port: 8765